version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  redis:
    image: redis
    container_name: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: springboot-mongo
    #    ports:  # for demo/debug purpose only
    #      - 27018:27017
    restart: always



